server:
  port: ${CACHE_PORT}

idealobridge:
  oAuth2ClientId: ${CLIENT_ID}
  oAuth2ClientSecret: ${CLIENT_SECRET}
  accessTokenURI: ${ACCESS_TOKEN_URI}
  apiUrl: ${API_URL}
  offerRoute: "offers/"

spring:
  data:
      mongodb:
        host: ${MONGO_IP}
        port: ${MONGO_PORT}
        username: ${MONGO_CACHE_USER}
        password: ${MONGO_CACHE_PW}
        database: cache